### PR TITLE
Update Nx to v17 and swap dev/peer dep `@nx/workspace` to `nx`

### LINKED ISSUE #27: Don't depend on @nx/workspace
The `tasks-runners/default` is available in the core `nx` package, there is no need to import it from an additional package.

### PR DESCRIPTION
**Pull request by rathpc**
This PR updates nx to the latest v17 and swaps the dev and peer nx dependencies from `@nx/workspace` to `nx` which fixes #27 

Changes have also been made to the `README.md` to update the compatibility chart, updates to the `CHANGELOG.md` and the new version of this package referenced in `package.json`.

### CODE REVIEW

**Comment by rathpc** [comment]
@NiklasPor when you have a chance, can you please take a look at this PR? I wanted to upgrade this library to the latest Nx version and as a result I thought we could also knock out a change requested in the current issues which seemed like a good change to make. If you don't think transitioning from `@nx/workspace` to `nx` should be done, please let me know and I will update my branch and PR to reflect that. Thank you!

**Comment by NiklasPor** [comment]
Awesome, I'll throughly test it and then create a new batch of releases. Thanks!

**Comment by rathpc** [comment]
> Awesome, I'll throughly test it and then create a new batch of releases. Thanks!

Hey @NiklasPor have you had a chance to test this yet?

**Comment by rathpc** [comment]
@NiklasPor Please let me know if there is anything I can do to help move this along, thanks!

**Comment by NiklasPor** [comment]
Seems to look fine. I'm just thinking about mirroring the major NX version, as this is getting more and more complicated - but that's not stopping me from merging this.

**Comment by NiklasPor** [comment]
I'll write an update here once the new version is available.

**Comment by NiklasPor** [comment]
`nx-remotecache-custom@17.0.0` and `nx-remotecache-azure@17.0.0` are now available, thanks for your contribution! I'm always happy about everyone keeping the project on-track 🙇 (nx-remotecache-minio follows next 😄 )

**Comment by rathpc** [comment]
Thank you so much!

**Pull request merged**
