### PR TITLE
filterMachineId for only root source file

### LINKED ISSUE #23: filterMachineId filters some required files
Hi, while using this lib at one of the projects at work i encountered an issue when cached standalone build of nextjs app wrapped with sentry throws an error in docker, my investigation lead to the conclusion that cached build was missing files for `chalk@3.0.0` because it has `source` dir which was missing in cached build.

The issue i think is with [this function](https://github.com/NiklasPor/nx-remotecache-custom/blob/main/lib/filter-machine-id.ts#L2) but i haven't really understood what it filters overall 

For reproduction of this problem i've made an example repo
https://github.com/EvgeniyKumachev/nx-cache-repro

### PR DESCRIPTION
**Pull request by EvgeniyKumachev**
fixes #23

### CODE REVIEW

**Comment by NiklasPor** [comment]
Thanks for the contribution, looks like this should work. I'll test, merge and release the change 👍

**Comment by EvgeniyKumachev** [comment]
@NiklasPor any progress with testing?

**Comment by NiklasPor** [comment]
Thanks for the ping, I'm testing it at this moment.

**Comment by NiklasPor** [comment]
While debugging why the latest version (incl. this change), isn't working – I stumbled upon a change in `16.9.0` which indicates that the check isn't necessary anymore at all. I'll check if that works.

**Comment by NiklasPor** [comment]
I completely removed the filtering as it will break with nx version `16.9.0` 🙄  Sorry for the long wait (also took some time to debug this) :|

**Pull request closed without merging**
