### PR TITLE
feat: add name option and NX_CACHE_NAME env variable to override implementation name

### LINKED ISSUE #6: Add optional `name` to RunnerOptions and `NX_CACHE_NAME` env var
https://github.com/NiklasPor/nx-remotecache-minio/blob/main/lib/index.ts#L55 outputs `Minio Storage` to the build logs.

In my situation it is advantageous to be able to override this name for CI/CD pipelines (connecting to a different Minio instance) using an ENV var such as `NX_CACHE_MINIO_NAME`, so that it's clearer to the users which cache is being used.

Nu hurry. Just a "nice to have".

### PR DESCRIPTION
**Pull request by minijus**
Closes #6

### CODE REVIEW

**Comment by minijus** [comment]
@NiklasPor could you have a look at this PR?

**Review by NiklasPor — CHANGES_REQUESTED** [review]
Looks good, thanks a lot for your contribution! ❤️ 
After the small adjustments, I'll merge it and create a new release.

**Comment by minijus** [comment]
@NiklasPor do you think this PR is ok to merge?

**Comment by NiklasPor** [comment]
I'll include this in the next releases 🚀  Thanks again!

**Pull request merged**
